spring:
  application:
    name: savt-backend
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/savt_db
      auto-index-creation: true

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

  access-token:
    expiration: 900000

  refresh-token:
    expiration: 604800000